export const proyectosDefault = [
    {
        id: 1,
        name: 'FARS Tech Solutions',
        description: 'Desarrollo de productos digitales',
        owner_id: 1,
        color: '#6366f1',
        is_archived: false,
    },
    {
        id: 2,
        name: 'Personal',
        description: 'Tareas y metas personales',
        owner_id: 1,
        color: '#f59e0b',
        is_archived: false,
    },
];

export const grillasDefault = [
    {
        id: 1,
        name: 'Por Hacer',
        position: 1,
        color: '#ef4444',
        proyect_id: 1,
    },
    {
        id: 2,
        name: 'En Progreso',
        position: 2,
        color: '#3b82f6',
        proyect_id: 1,
    },
    {
        id: 3,
        name: 'Revisión',
        position: 3,
        color: '#f59e0b',
        proyect_id: 1,
    },
    {
        id: 4,
        name: 'Completado',
        position: 4,
        color: '#22c55e',
        proyect_id: 1,
    },
    {
        id: 5,
        name: 'Ideas',
        position: 1,
        color: '#8b5cf6',
        proyect_id: 2,
    },
    {
        id: 6,
        name: 'En Curso',
        position: 2,
        color: '#06b6d4',
        proyect_id: 2,
    },
];

export const tareasDefault = [
    {
        id: 1,
        grilla_id: 1,
        title: 'Diseñar landing page',
        description: 'Crear wireframes y mockups para la nueva landing',
        position: 1,
        assigned_to: 1,
        start_date: new Date().toISOString(),
        due_date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
        priority: 'Alta',
        created_by: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 2,
        grilla_id: 1,
        title: 'Configurar CI/CD',
        description: 'Pipeline de deployment automático',
        position: 2,
        assigned_to: 1,
        start_date: new Date().toISOString(),
        due_date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
        priority: 'Media',
        created_by: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 3,
        grilla_id: 2,
        title: 'Implementar auth',
        description: 'Login con Google y GitHub OAuth',
        position: 1,
        assigned_to: 1,
        start_date: new Date().toISOString(),
        due_date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
        priority: 'Alta',
        created_by: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: 4,
        grilla_id: 4,
        title: 'Setup del repositorio',
        description: 'Estructura inicial del monorepo',
        position: 1,
        assigned_to: 1,
        start_date: new Date().toISOString(),
        due_date: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
        priority: 'Baja',
        created_by: 1,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];